config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      get :quote
    end
  end
  resources :users
  resources :microposts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :reposts,             only: [:create, :destroy]
  resources :comments,            only: [:create]
  resources :likes,               only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  belongs_to :parent, class_name: "Micropost", optional: true
  has_many :children, class_name: "Micropost",
                    foreign_key: "parent_id"
  has_many :reposts
  has_many :likes
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: "must be a valid image format" },
                    size:         { less_than: 5.megabytes,
                                    message: "should be less than 5MB" }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  # Returns the users that the given user follows that have reposted a certain micropost
  def followings_who_reposted(user)
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    repost_ids = "SELECT user_id FROM reposts
                  WHERE micropost_id = :micropost_id"
    User.where("id IN (#{following_ids})
                AND id IN (#{repost_ids})", user_id: user.id, micropost_id: id)
  end

  # Returns quotes
  def quotes
    children.where(relationship_type: 0)
  end

  # Returns comments
  def comments
    children.where(relationship_type: 1)
  end

  # Returns total number of quotes and reposts
  def rqcount
    reposts.count + quotes.count
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @microposts = Micropost.where(Micropost.arel_table[:content].matches("%#{params[:search_term]}%")).paginate(page: params[:page])
  end

  def show
    @micropost = Micropost.where(id: params[:id]).first
    if @micropost
      @comment = @micropost.children.build
      @comments = @micropost.children.where(relationship_type: 1).paginate(page: params[:page])
    else
      redirect_to root_url
    end
  end

  def quote
    @parent = Micropost.find(params[:id])
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      if @micropost.relationship_type == 1
        flash[:success] = "Comment created!"
        redirect_to @micropost.parent
      else
        flash[:success] = "Micropost created!"
        redirect_to root_url
      end
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])
    @micropost.image.attach(params[:micropost][:image]) unless params[:micropost][:image].nil?
    if @micropost.update(micropost_params)
      flash[:success] = "Micropost updated"
      redirect_to @micropost
    else
      render 'edit'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image, :parent_id, :relationship_type)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_like.html.erb
<%= link_to t('Like'), likes_path(micropost_id: micropost.id), method: :post, remote: true %>

app/views/microposts/_like_form.html.erb
<span class="like_link-<%= micropost.id %>">
  <% if current_user.liked?(micropost) %>
    <%= render 'microposts/unlike', micropost: micropost %>
  <% else %>
    <%= render 'microposts/like', micropost: micropost %>
  <% end %>
</span>

app/views/microposts/_micropost.html.erb
<% unless defined? parent %>
  <li id="micropost-<%= micropost.id %>">
<% else %>
  <div class="parent_micropost">
<% end %>
    <% unless defined? dont_show_who_reposted or
              @user.following?(micropost.user) or
              @user == micropost.user or
              defined? parent %>
        <%= micropost.followings_who_reposted(@user).first.name %>
        <%= (micropost.followings_who_reposted(@user).count > 1 ? 'and others' : '') %>
        reposted this<br><br>
    <% end %>
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content">
      <%= micropost.content %>
      <%= image_tag micropost.display_image, class: 'content-img' if micropost.image.attached? %>
      <%= render 'microposts/parent', micropost: micropost unless micropost.parent_id.nil? or defined? parent  %>
    </span>
    <span class="timestamp">
      <%= time_ago_in_words(micropost.created_at) + t('ago') %>
      <span class="repost_count-<%= micropost.id %>">
        <%= pluralize(micropost.rqcount, t('repost')) %>
      </span>
      <span class="comment_count-<%= micropost.id %>">
        <%= pluralize(micropost.comments.count, t('comment')) %>
      </span>
      <span class="like_count-<%= micropost.id %>">
        <%= pluralize(micropost.likes.count, t('like')) %>
      </span>
      <%= link_to t("Quote"), quote_micropost_path(id: micropost.id) if logged_in? %>
      <%= render 'microposts/repost_form', micropost: micropost if logged_in? %>
      <%= link_to t("Comment"), micropost if logged_in? %>
      <%= render 'microposts/like_form', micropost: micropost if logged_in? %>
      <% if current_user?(micropost.user) %>
        <%= link_to t("Delete"), micropost, method: :delete,
                                         data: { confirm: "You sure?" } %>
      <% end %>
      <%= link_to t("Edit"), edit_micropost_path(micropost) if current_user?(micropost.user) %>
    </span>
<% unless defined? parent %>
  </li>
<% else %>
  </div>
<% end %>

app/views/microposts/_parent.html.erb
<% unless micropost.parent.nil? %>
  <%= render micropost.parent, parent: true, dont_show_who_reposted: true %>
<% else %>
  <div style="border: solid"><%= t("post_is_deleted") %></div>
<% end %>

app/views/microposts/_repost.html.erb
<%= link_to t('Repost'), reposts_path(micropost_id: micropost.id), method: :post, remote: true %>

app/views/microposts/_repost_form.html.erb
<span class="repost_link-<%= micropost.id %>">
  <% if current_user.reposted?(micropost) %>
    <%= render 'microposts/unrepost', micropost: micropost %>
  <% else %>
    <%= render 'microposts/repost', micropost: micropost %>
  <% end %>
</span>

app/views/microposts/_unlike.html.erb
<%= link_to t('Unlike'), current_user.likes.find_by(micropost_id: micropost.id), method: :delete, remote: true %>

app/views/microposts/_unrepost.html.erb
<%= link_to t('Unrepost'), current_user.reposts.find_by(micropost_id: micropost.id), method: :delete, remote: true %>

app/views/microposts/edit.html.erb
<% provide(:title, 'Edit micropost') %>

<h3><%= t("edit_micropost") %></h3>
<% unless @micropost.parent.nil? %>
  <div class="microposts">
    Parent micropost:<br>
    <%= render @micropost.parent, dont_show_who_reposted: true %>
  </div>
  <hr>
<% end %>

<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("new_micropost") %>
  </div>

  <%= image_tag @micropost.image.attached? ? @micropost.image : '', id: 'img_prev' %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <%= f.submit t("Save"), class: "btn btn-primary" %>
<% end %>

<%= javascript_pack_tag 'image_size_check' %>

app/views/microposts/index.html.erb
<% provide(:title, 'All microposts') %>
<h1><%= t("all_microposts") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: microposts_path, method: :get, local: true) do |f| %>

      <%= f.label :search_term, t("search_microposts") %>
      <%= f.text_field :search_term, class: 'form-control' %>

      <%= f.submit t("Search"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= will_paginate %>

<ol class="microposts">
  <%= render @microposts, dont_show_who_reposted: true %>
</ol>

<%= will_paginate %>

app/views/microposts/quote.html.erb
<% provide(:title, 'Quote micropost') %>

<div class="microposts">
  <%= t("parent_micropost") %>:<br>
  <%= render @parent, dont_show_who_reposted: true %>
</div>
<hr>

<%= form_with(model: current_user.microposts.build, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :parent_id, value: @parent.id %>
  <%= f.hidden_field :relationship_type, value: 0 %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("quote_micropost") %>
  </div>
  <%= image_tag '', id: 'img_prev' %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <%= f.submit t("Post"), class: "btn btn-primary" %>
<% end %>

<%= javascript_pack_tag 'image_size_check' %>

app/views/microposts/show.html.erb
<% provide(:title, 'Viewing micropost') %>

<div class="microposts">
  <%= render @micropost, dont_show_who_reposted: true %>
</div>
<hr>

<h3>Comments (<%= @comments.count %>)</h3>
<% if @comments.any? %>
  <ol class="comments">
    <%= render @comments, dont_show_who_reposted: true, parent: true %>
  </ol>
  <%= will_paginate @comments %>
<% end %>

<%= form_with(model: @comment, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :parent_id, value: @micropost.id %>
  <%= f.hidden_field :relationship_type, value: 1 %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("comment_micropost") %>
  </div>
  <%= image_tag '', id: 'img_prev' %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <%= f.submit t("Post"), class: "btn btn-primary" %>
<% end %>

<%= javascript_pack_tag 'image_size_check' %>